server:
  port: 8080
  forward-headers-strategy: native

spring:
  config:
    activate:
      on-profile: prod
  
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update


app:
  env: prod

sentry:
  dsn: ${SENTRY_DSN:}
  traces-sample-rate: 0.1
  exception-resolver-order: 1
  logging:
    mdc-tags: request_id,user_id,meeting_id,fcm_token